#!/usr/bin/env bash
# Script that creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/holbertonscript.pid

trap "echo I hate the kill command; exit_f" 15
trap "Y U no love me?!" 2
trap "exit_f" 3

exit_f()
{
    rm /var/run/holbertonscript.pid
    exit
}

while ((1))
do
    echo "To infinity and beyond"
    sleep 2
done
